"""Add phone_number column to User table

Revision ID: 034131d147fa
Revises: f203c960f90a
Create Date: 2023-05-24 11:29:25.012456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034131d147fa'
down_revision = 'f203c960f90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
