"""Change data type of profile_picture column

Revision ID: 682172d1ed66
Revises: 034131d147fa
Create Date: 2023-05-24 11:33:26.432269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682172d1ed66'
down_revision = '034131d147fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
