"""empty message

Revision ID: 6d95ae1e3813
Revises: 24ec6d9b5684
Create Date: 2023-06-20 10:15:11.567586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d95ae1e3813'
down_revision = '24ec6d9b5684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonymous_snake_game_leaderboard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_snake_game_leaderboard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
